### ISSUE TITLE
Problems with update

### ISSUE THREAD

**Issue by Bustami** [JoGall/soccermatics#16]
Hi there
I'm tryng to use the last updates but i got some errors:

> Error in soccerShotmap(., theme = "grass", colGoal = "yellow", colMiss = "blue",  : 
  unused arguments (colGoal = "yellow", colMiss = "blue", legend = T)

> Error in soccerPassmap(., fill = "blue", minPass = 3, edge_max_width = 30,  : 
  unused arguments (edge_max_width = 30, edge_col = "grey40", edge_alpha = 1)

I installed the 0.9.3 version. Is it the last version?

Thanks

**Comment by JoGall** [comment]
Whoops, didn't mean to push the tarball for 0.9.3! If you're after the latest version, just use `devtools` to install from source.

**Comment by Bustami** [comment]
Thanks!
The problem now is devtools function "install_github" has a bug, so i got:
`devtools::install_github("jogall/soccermatics")`

> Error in read.dcf(path) : 
>   Found continuation line starting '    'soccerFlipDirec ...' at begin of record.

Coul you update the .tar.gz file in order to donwload and install it locally?

**Comment by JoGall** [comment]
Hmm it sounds like the documentation might have been malformed but I can't see what -- maybe some unexpected Git merging behaviour as I develop on both Linux and Windows.

Can you try using `devtools` one more time? I've updated the tarball (v0.9.3) but think the issue will affect that too if it persists..

**Comment by Bustami** [comment]
Yep. I tried again and got a different error:

> Error in parse(outFile) : 
  .../AppData/Local/Temp/Rtmpw9fJrK/devtools296865146a03/JoGall-soccermatics-7a3c9d2/R/soccerxGTimeline.R:126:1: inesperado '=='
125: }
126: ==
     ^

**Comment by JoGall** [comment]
Mais uma vez, por favor..

**Comment by Bustami** [comment]
Another error:
> Error in read.dcf(path) : 
  Found continuation line starting '    'soccerFlipDirec ...' at begin of record

I also downloaded the 0.9.3 tar and suchesfully install it locally, but it doesn't have the arguments from update. 

Anyway, i could do some viz without these arguments. Don't worry. Thanks mate!
