### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by arsc99** [JoGall/soccermatics#17]
>  devtools::install_github("jogall/soccermatics")
Error in read.dcf(path) : Found continuation line starting '    'soccerFlipDirec ...' at begin of record.

**Comment by JoGall** [comment]
I've pushed some changes -- can you try installing again please?

**Comment by arsc99** [comment]
Still has the same problem...

**Comment by JoGall** [comment]
Sorry but can you try one more time?

If it's still throwing an error, can you please give me your OS and R version.

**Comment by arsc99** [comment]
Thank you for your help!
Now it has a different problem...

Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Trabalho/AppData/Local/Temp/Rtmp8W3s1A/filed787b814da6/soccermatics_0.9.3.tar.gz’ had non-zero exit status

I'm using R 3.5.1 on Windows

**Comment by JoGall** [comment]
Can you try using `devtools::install_github("jogall/soccermatics")` instead of the tarball?

**Comment by JoGall** [comment]
You need dependency `cowplot` first:

`install.packages("cowplot")`

**Comment by arsc99** [comment]
Man, you're the best! After that, I had to install several other packages but it's finally working!
Thank you so much!

**Comment by JoGall** [comment]
No worries mate, glad we finally got there! 😀

**Comment by iambinnie** [comment]
install.packages("ggforce")
install.packages("ggrepel")
install.packages("xts")
are other dependencies that are required to be added.
There may be more which I already had installed.
