### ISSUE TITLE
soccerSpokes doesn't work and usage sample is not correct

### ISSUE THREAD

**Issue by davidfombella** [JoGall/soccermatics#3]
When using soccerSpokes generates this message
soccerSpokes(subset(tromso, id == 8), bins = 15, lengthPitch = 105, widthPitch = 68,heatmap = FALSE)
**Error in 1:n : NA/NaN argument**

*********************************
help displays soccerHeatmap help page as usage example
help(soccerSpokes)

Examples

## Not run: 
data(tromso)
# draw heatmap of player #9's position
soccerHeatmap(subset(tromso, id == 8), bins = 15)

**Comment by JoGall** [comment]
Thanks for the heads up. The `soccerSpokes` function should work now and I've added a `soccerFlow` function for summarising mean angle in each area of the pitch.

**Comment by davidfombella** [comment]
No Joe, no on another laptop, I can't even install package.

files in 'C:/Users/dpomb/AppData/Local/Temp/RtmpisTfHK/devtools900751360cd/JoGall-soccermatics-7de0445/R' missing from 'Collate' field:
  soccerSpokes.R
**ERROR: unable to collate and parse R files for package 'soccermatics'**
* removing 'C:/Users/dpomb/Documents/R/win-library/3.4/soccermatics'
Installation failed: Command failed (1)
