### ISSUE TITLE
Error on installation 

### ISSUE THREAD

**Issue by davidfombella** [JoGall/soccermatics#5]
* installing *source* package 'soccermatics' ...
** R
**Error in .install_package_code_files(".", instdir) : 
files in 'C:/Users/dpomb/AppData/Local/Temp/RtmpisTfHK/devtools900751360cd/JoGall-soccermatics-7de0445/R' missing from 'Collate' field:
  soccerSpokes.R
ERROR: unable to collate and parse R files for package 'soccermatics'**
* removing 'C:/Users/dpomb/Documents/R/win-library/3.4/soccermatics'
Installation failed: Command failed (1)
> devtools::install_github("jogall/soccermatics")

**Comment by JoGall** [comment]
Can you try reinstalling the package? I've overhauled the `soccerSpokes()` function and it seems to work now, at least for me.

**Comment by davidfombella** [comment]
Yes, now works. Please I send you a mail , trying to check if given x,y,time utc , you can help me to calculate speed,angle, acceleration to be able to test soccerSpokes and soccerFlow, it is raw data from stadium cameras.

**Comment by davidfombella** [comment]
Now error is on this file
 **Error in .install_package_code_files(".", instdir) : 
files in 'Collate' field missing from 'C:/Users/dpomb/AppData/Local/Temp/RtmpWisOsT/devtools31a83d191083/JoGall-soccermatics-ff94e4e/R':
  pipe.R**
ERROR: unable to collate and parse R files for package 'soccermatics'
* removing 'C:/Users/dpomb/Documents/R/win-library/3.4/soccermatics'
* restoring previous 'C:/Users/dpomb/Documents/R/win-library/3.4/soccermatics'
Installation failed: Command failed (1)

**Comment by JoGall** [comment]
The issue with pipe.R should be fixed now if you reinstall.

As for extracting speed and heading angle from raw x,y,t-data, see [this gist](https://gist.github.com/JoGall/a34a1430590a17655a36a7a2d467ff1c) for an example.

Speed is just the Pythogarian distance between successive x,y-points divided by the time interval, and heading angle can be calculated using [atan2](https://en.wikipedia.org/wiki/Atan2).

I may add a function to the package for calculating these soon.

**Comment by davidfombella** [comment]
On soccer spokes fails, since I have a time column
Error in assert_all_white_list(data) : 
  Column `utc` is of unsupported class POSIXlt/POSIXt

**Comment by JoGall** [comment]
Have you tried excluding the time column from your input data? i.e. `soccerSpokes(data[,c("x", "y")])`

The function shouldn't be handling time variables anyway so I'll update it soon.
