### ISSUE TITLE
Soccermatics not available for R version 3.4.2

### ISSUE THREAD

**Issue by FintanMi** [JoGall/soccermatics#6]
Does this only work on earlier versions or do I need to install some other package?

**Comment by JoGall** [comment]
I'm working on a fix for this. The package was built on R version 3.3. which I can't seem to upgrade (on Ubuntu 16.04).

There will be some way around it, I'll update here when I find out!

**Comment by JoGall** [comment]
Can you try installing again? I've now built the package with v3.4.2 and seems to work on my end. If it still fails there's now a binary [here](https://github.com/JoGall/soccermatics/blob/master/soccermatics_0.8.4.tar.gz) you can try installing from instead.

**Comment by JoGall** [comment]
No worries, enjoy!
